backend:
  name: git-gateway
  branch: master
collections:
  - name: routes
    label: routes
    folder: src/routes
    create: true
    fields:
      - name: title
      - name: nav_label
      - name: body
        widget: markdown
media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://childrens-book.netlify.app
display_url: https://childrens-book.netlify.app
logo_url: https://childrens-book.netlify.app/images/logo.svg