backend:
    name: git-gateway
    branch: master
collections:
    -   name: blog
        label: "Blog Posts"
        folder: src/routes/blog
        create: true
        fields:
            -   name: title
            -   name: body
                widget: markdown
    -   name: general
        label: "General Configuration"
        files: 
            -   name: store
                label: Store
                file: "src/lib/data/products.json" 
                fields: 
                    -   name: products 
                        label: "Products"
                        widget: list
                        fields: 
                            - { label: "API ID", name: apiId, widget: string }
            

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://childrens-book.netlify.app
display_url: https://childrens-book.netlify.app
logo_url: https://childrens-book.netlify.app/images/logo.svg