backend:
    name: github
    repo: tomatrow/childrens-book-site
    use_graphql: true

local_backend: true

collections:
    - name: posts
      label: "Blog Posts"
      label_singular: "Blog Post"
      folder: "src/lib/data/posts"
      create: true
      identifier_field: "handle"
      format: "json"
      fields:
          - { label: "Post Handle", name: handle, widget: string }
          - { label: "Post Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }
    - name: products
      label: "Products"
      label_singular: "Product"
      folder: "src/lib/data/products"
      create: true
      identifier_field: "handle"
      format: "json"
      fields:
          - { label: "Product Handle", name: handle, widget: string }
          - { label: "API Product ID", name: id, widget: string }
          - { label: "Body", name: body, widget: markdown }
    - name: pages
      label: "Pages"
      label_singular: "Page"
      folder: "src/lib/data/pages"
      create: true
      identifier_field: "handle"
      format: "json"
      fields:
          - { label: "Page Handle", name: handle, widget: string }
          - { label: "Page Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }
    - name: collections
      label: "Collections"
      label_singular: "Collection"
      folder: "src/lib/data/collections"
      create: true
      identifier_field: "handle"
      format: "json"
      fields:
          - { label: "Collection Handle", name: handle, widget: string }
          - { label: "Collection Title", name: title, widget: string }
          - { label: "Body", name: body, widget: markdown }
          - label: "Products"
            name: products
            widget: list
            fields:
                - { label: "Product Handle", name: handle, widget: string }

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://childrens-book.netlify.app
display_url: https://childrens-book.netlify.app
logo_url: https://childrens-book.netlify.app/images/logo.svg
